kind: Deployment
apiVersion: apps/v1
metadata:
  name: django-deployment
  namespace: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: gopesh13/django-notes-app
        ports:
        - containerPort: 8001
